---
title: "Index of stocks.Rmd"
author: "kireihei"
date: "09/04/2021"
output: html_document
---

Load required packages
```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(lubridate)
library(tibble)
```

Set workpath and load datasets
```{r}
setwd("C://Gggggg//MSc in Finance EMLYON//Data Science R//Project")
load("data_esg.RData")
load("data_full.RData")
head(data_full)
summary(data_full)
```

Set up the index table
```{r}
data_index <- data_full %>%  
  mutate(Position = 100/Close) %>% 
  arrange(Date)

# print(unique(data_index$Date))
# for(ii in unique(data_index$Date)){
#   print(ii)
# }

for(i in unique(data_index$Tick)){  # select the Tick
  for(ii in unique(data_index$Date)){  # select the Date
    ii <- as.Date(ii, origin="1970-01-01")
    if(ii != min(data_index$Date)){
      data_index[data_index$Tick == i & data_index$Date == ii,]$Position[1] = data_index[data_index$Tick == i & data_index$Date == min(data_index$Date),]$Position[1]
    #print(data_index[data_index$Tick == i & data_index$Date == ii])
    } else {}
}
}

head(data_index)
```
