---
title: "Project - Wenxuan Sun"
author: "Wenxuan Sun"
date: "09/04/2021"
output: html_document
---

Load required packages
```{r}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(lubridate)
library(tibble)
```

Set workpath and load datasets
```{r}
setwd("C://Gggggg//MSc in Finance EMLYON//Data Science R//Project")
load("data_esg.RData")
load("data_full.RData")
head(data_full)
summary(data_full)
```
Set up the index table
```{r}
data_full <- data_full %>% 
  arrange(Date) 
data_full$Date <- as.Date(data_full$Date, origin="1970-01-01")
min_date <- min(data_full$Date)

# print(length(unique(data_full$Date)))

c100 <- rep(100, length(data_full[data_full$Date == min_date, ]$Close))
close_1 <- data_full[data_full$Date == min_date, ]$Close
Position <- c100 / close_1
print(length(Position))  # positions for 928 stocks

# index = position * price
index_1 <- t(Position) %*% close_1  # index at the beginning

data_index <- data.frame(Date=min_date, Index=index_1)
print(data_index)

for(i in unique(data_full$Date)){
  i <- as.Date(i, origin="1970-01-01")
  if(i != min_date){
    close_i <- data_full[data_full$Date == i, ]$Close
    index_i <- t(Position) %*% close_i
    print(index_i)
    data_index_i <- data.frame(Date=i, Index=index_i)
    data_index <- rbind(data_index, data_index_i)
  } else {}
}

head(data_full)
```



